apiVersion: v1
kind: Service
metadata:
  name: library-client
  labels:
    app: library-client
spec:
  type: LoadBalancer
  selector:
    app: library-client
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
