version: "3.3"
services:
  client:
    container_name: library-client
    build: ./client
    ports:
      - 9000:9000
    networks:
      - library-app
    depends_on:
      - server
    env_file: ./client/.env
    restart: always
  server:
    container_name: library-server
    build: ./server
    ports:
      - 5000:5000
    networks:
      - library-app
    depends_on:
      - db
    env_file: ./server/.env
    restart: always
  db:
    container_name: library-db
    image: postgres:14
    ports:
      - 5432:5432
    networks:
      - library-app
    env_file: ./server/.env
    restart: always
networks:
  library-app:
    driver: bridge
