version: "3.3"
services:
  server:
    container_name: library-server
    build: ./server
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - db
    env_file: ./server/.env
    restart: always
  db:
    container_name: library-db
    image: postgres:14
    ports:
      - 5432:5432
    networks:
      - backend
    env_file: ./server/.env
    restart: always
networks:
  backend:
    driver: bridge
