# File: grafana-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |-
    [server]
    http_addr = 0.0.0.0
    http_port = 3000
    # Add additional Grafana configurations as needed
