# File: client-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: library-client-pod
spec:
  containers:
    - name: library-client-container
      image: your-registry/library-client:latest
      ports:
        - containerPort: 9000
  envFrom:
    - configMapRef:
        name: library-client-configmap
    - secretRef:
        name: library-client-secret
  restartPolicy: Always
---
# File: server-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: library-server-pod
spec:
  containers:
    - name: library-server-container
      image: your-registry/library-server:latest
      ports:
        - containerPort: 5000
  envFrom:
    - configMapRef:
        name: library-server-configmap
    - secretRef:
        name: library-server-secret
  restartPolicy: Always
---
# File: db-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: library-db-pod
spec:
  containers:
    - name: library-db-container
      image: postgres:14
      ports:
        - containerPort: 5432
  envFrom:
    - configMapRef:
        name: library-db-configmap
    - secretRef:
        name: library-db-secret
  restartPolicy: Always
