FROM python:3.9-slim-buster
WORKDIR /server

COPY requirements.txt requirements.txt
RUN python3.9 -m pip install -r requirements.txt

COPY /src .

CMD ["flask", "--app", "app.py", "--debug", "run", "--host=0.0.0.0"]
