apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-server
  template:
    metadata:
      labels:
        app: library-server
    spec:
      containers:
        - name: library-server
          image: ardisyahputra12/library-server:latest
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: POSTGRES_PASSWORD
