apiVersion: v1
kind: Service
metadata:
  name: library
  labels:
    app: library
spec:
  type: LoadBalancer
  selector:
    app: library
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
